service:
  extensions: [jaeger_storage, jaeger_query]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [jaeger_storage_exporter]

extensions:
  jaeger_query:
    trace_storage: some-storage
    ui_config: ./cmd/jaeger/config-ui.json

  jaeger_storage:
    backends:
      some-storage:
        grpc:
          endpoint: localhost:17271
          tls:
            insecure: true

receivers:
  otlp:
    protocols:
      grpc:
      http:

processors:
  batch:

exporters:
  jaeger_storage_exporter:
    trace_storage: some-storage
