name: Lint Shell Scripts

on:
  push:
    branches: [main]

  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  link-shell-scripts:
    runs-on: ubuntu-latest

    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@0d381219ddf674d61a7572ddd19d7941e271515c # v2.9.0
      with:
        egress-policy: audit

    - name: Check out code
      uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

    - name: Install shellcheck
      run: sudo apt-get install shellcheck

    - name: Run shellcheck
      run: shellcheck scripts/*.sh

    - name: Install shunit2
      uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      with:
        repository: kward/shunit2
        path: .tools/shunit2

    - name: Run unit tests for scripts
      run: |
        SHUNIT2=.tools/shunit2 bash scripts/compute-tags.test.sh
