name: Unit Tests on Go Tip

on:
  push:
    branches: [main]

permissions:
  contents: read

jobs:
  unit-tests-go-tip:
    permissions:
      checks: write
    runs-on: ubuntu-latest
    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@0d381219ddf674d61a7572ddd19d7941e271515c # v2.9.0
      with:
        egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs

    - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

    - name: Install Go Tip
      uses: ./.github/actions/setup-go-tip

    - name: Install test deps
      # even though the same target runs from test-ci, running it separately makes for cleaner log in GH workflow
      run: make install-test-tools

    - name: Run unit tests
      run: make test-ci

    - name: Lint
      run: echo skip linting on Go tip
