name: Unit Test Results

on:
  workflow_run:
    workflows: ["Unit Tests", "Unit Tests on Go Tip"]
    types:
      - completed

jobs:
  unit-test-results:
    name: ${{ github.event.workflow_run.name }}
    runs-on: ubuntu-latest
    if: github.event.workflow_run.conclusion != 'skipped'

    permissions:
      checks: write

      # Needed unless run with comment_mode: off.
      pull-requests: write

      # Required by download step to access artifacts API.
      actions: read

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@eb238b55efaa70779f274895e782ed17c84f2895 # v2.6.1
        with:
          egress-policy: audit # TODO: change to 'egress-policy: block' after a couple of runs

      - name: Download and Extract Artifacts
        uses: dawidd6/action-download-artifact@v3
        with:
          run_id: ${{ github.event.workflow_run.id }}
          path: artifacts

      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        with:
          commit: ${{ github.event.workflow_run.head_sha }}
          event_file: artifacts/Event File/event.json
          event_name: ${{ github.event.workflow_run.event }}
          files: "artifacts/**/*.xml"
