name: Validation Of Shell Scripts

on:
  push:
    branches: [main]

  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  validation-of-shell-scripts:
    runs-on: ubuntu-latest

    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@eb238b55efaa70779f274895e782ed17c84f2895 # v2.6.1
      with:
        egress-policy: audit

    - name: check out code 
      uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

    - name: Install shellcheck
      run: sudo apt-get install shellcheck

    - name: Run shellcheck
      run: shellcheck scripts/*.sh






